### ISSUE TITLE
Query : using json input inside a select query ?

### ISSUE THREAD

**Issue by VanAxl** [tonymorello/n8n-nodes-ibmi-db2#1]
Hello, 

I've used  your node in my n8n docker installation. It works pretty well.
I can run a static query and get the result.

But now I'm trying to adjust that query based on an input. 
So I've modified my query with a basic input, adding some {{ json.xxx }} inside the query itself. It seems that the node is not using the result of the JS code I put, but the code itself in the query : 

<img width="1482" alt="image" src="https://github.com/tonymorello/n8n-nodes-ibmi-db2/assets/45239924/5610a89b-ccb9-47a4-85a3-9b5058e94995">

As we can see in the screenshot, it should answer 'ADAVID' in my output result but instead it results the ' {{ json.xxx}}' code.
I don't know if I'm doing something wrong is if there is a limitation on that module ?
Can you help ?
THanks
Regards
Nicolas

**Comment by VanAxl** [comment]
I've also posted in the n8n community forum, but it seems that issue is related to the node itself  !

**Comment by tonymorello** [comment]
@VanAxl yeah, I have made a mistake in how the query string is processed. I am fixing it and will publish the update as soon as I am done.

Thanks for letting me know

**Comment by tonymorello** [comment]
Fixed in release 1.0.3

**Comment by VanAxl** [comment]
Thanks @tonymorello .
I've checked this version 1.0.3 .But it seems the result is the same :

<img width="1887" alt="image" src="https://github.com/tonymorello/n8n-nodes-ibmi-db2/assets/45239924/aa3fe818-429a-4a18-bd88-88a8367acd83">


I've tried to run a simple query, the preview/result in the middle of the screen is understanding my $json.subject correctly. But the output of the node is still giving the {{ $json.subject }} instead tof the "user" value. 
So if I tried to use this Subject value to the Where statement of my query it doesn't work.
Thanks for your help.

**Comment by tonymorello** [comment]
Make sure you restart your n8n instance and refresh the browser cache. I've noticed while making changes to the node some times it does not pick them up right away. I can't replicate your issue in v1.0.3 (see below)

![image](https://github.com/tonymorello/n8n-nodes-ibmi-db2/assets/7967400/75ef0cd7-195c-4dca-bd10-2d4d5ce2bf22)

**Comment by VanAxl** [comment]
Thanks @tonymorello , you were right, updating the node was not enough. I'v completely restarted my n8n docker and now it simply works. 
Super ! good job !
