### ISSUE TITLE
Can't install node

### ISSUE THREAD

**Issue by mika133** [tonymorello/n8n-nodes-ibmi-db2#2]
Hello 
I would like to use IBM DB 2 to execute queries on my workflow but when i try to install i got this error :
 

![image](https://github.com/tonymorello/n8n-nodes-ibmi-db2/assets/44366522/f2d20780-72d3-4f64-b2a0-f3a2bfb160e6)

n8n version: Version 1.25.1
Database (default: SQLite): SQLite
n8n EXECUTIONS_PROCESS setting (default: own, main): default
Running n8n via (Docker, npm, n8n cloud, desktop app): Docker
Operating system: Win server 2022

**Comment by tonymorello** [comment]
Can you post the entire content of the error message?

**Comment by mika133** [comment]
Yes : 
`Error loading package "n8n-nodes-ibmi-db2" :The specified package could not be loaded Cause: Cannot find module '../build/jvm_dll_path.json' Require stack: - /home/node/.n8n/nodes/node_modules/java/lib/nodeJavaBridge.js - /home/node/.n8n/nodes/node_modules/java/index.js - /home/node/.n8n/nodes/node_modules/node-jt400/dist/lib/ifs/write_stream.js - /home/node/.n8n/nodes/node_modules/node-jt400/dist/lib/ifs/index.js - /home/node/.n8n/nodes/node_modules/node-jt400/dist/lib/jt400.js - /home/node/.n8n/nodes/node_modules/n8n-nodes-ibmi-db2/dist/nodes/IbmiDb2/GenericFunctions.js - /home/node/.n8n/nodes/node_modules/n8n-nodes-ibmi-db2/dist/nodes/IbmiDb2/IbmiDb2.node.js - /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/ClassLoader.js - /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/index.js - /usr/local/lib/node_modules/n8n/dist/config/schema.js - /usr/local/lib/node_modules/n8n/dist/config/index.js - /usr/local/lib/node_modules/n8n/dist/commands/start.js - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/plugin.js - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/config.js - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/index.js - /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js - /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/index.js - /usr/local/lib/node_modules/n8n/bin/n8n`

**Comment by tonymorello** [comment]
Seems to be an issue with running n8n in a docker container. This package depends on node-jt400 which in turn has other dependencies. I spun a quick docker container on my local environment and I was able to replicate the issue. In my case it fails to install with an error pointing at python missing from the path environment (not installed by default in the n8n docker image) which is required by node-gyp to build whatever is needed by node-jt400 to work... 

So for the time being I guess the package only works if you run n8n via npm. I will look for a possible solution as soon as I have some time.

**Comment by mika133** [comment]
Thank you
I've made a fresh install of n8n with npm and still can't install but message is different : 
"Error loading package "n8n-nodes-ibmi-db2" :Package could not be installed - check logs for details"

I've no further informations, even in log file.
Installation was made on linux in a first time then on a Windows server, same problem on both

**Comment by tonymorello** [comment]
Could you try and run `npm install n8n-nodes-ibmi-db2` just to see if it errors out, and paste the error log here?

**Comment by mika133** [comment]
Yes : 
`npm ERR! code 1
npm ERR! path C:\Windows\system32\node_modules\java
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.2 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.34407.143) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'C:\\Windows\\System32\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Windows\\system32\\node_modules\\java\\build\\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Windows\\System32\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\admdom1\\AppData\\Local\\node-gyp\\Cache\\20.11.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\\Users\\admdom1\\AppData\\Local\\node-gyp\\Cache\\20.11.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\\Windows\\System32\\node_modules\\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\admdom1\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.11.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=C:\\Windows\\system32\\node_modules\\java',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'C:\\Windows\\system32\\node_modules\\java\\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (C:\Windows\System32\node_modules\node-gyp\lib\configure.js:271:18)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.20348
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Windows\system32\node_modules\java
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok`

**Comment by tonymorello** [comment]
Alright... I ran some more tests. Node-JT400/node-gyp needs `g++` and `make` on Linux to be able to install the necessary dependencies. On Windows you'll need the Windows Build Tools installed.

Please refer to the **[Installation](https://github.com/joeferner/node-java?tab=readme-ov-file#installation)** section of `node-java` and this **[issue](https://github.com/tryggingamidstodin/node-jt400/issues/26)** from `node-jt400` for some context.

**Comment by mika133** [comment]
Hi, 
Thank you for your work, I managed to install it. Java version was too old and some packages as you mentionned were missing.
It's working great now, thank you

**Comment by tonymorello** [comment]
@mika133 just in case you'd like to run it in Docker I added a workaround to the Readme with steps to create a custom Docker image, It seems to be working fine for me. Obviously you'll have to rebuild it every time there is an update to the n8n base image.
